package moddedmite.xylose.bettergamesetting.client.audio;

import net.minecraft.ResourceLocation;

public class SoundEvents {
    public static final SoundEvent AMBIENT_CAVE;
    public static final SoundEvent BLOCK_ANVIL_BREAK;
    public static final SoundEvent BLOCK_ANVIL_LAND;
    public static final SoundEvent BLOCK_ANVIL_USE;
    public static final SoundEvent ENTITY_ARMORSTAND_BREAK;
    public static final SoundEvent ENTITY_ARMORSTAND_FALL;
    public static final SoundEvent ENTITY_ARMORSTAND_HIT;
    public static final SoundEvent ENTITY_ARROW_HIT;
    public static final SoundEvent ENTITY_ARROW_SHOOT;
    public static final SoundEvent ENTITY_BAT_AMBIENT;
    public static final SoundEvent ENTITY_BAT_DEATH;
    public static final SoundEvent ENTITY_BAT_HURT;
    public static final SoundEvent ENTITY_BAT_LOOP;
    public static final SoundEvent ENTITY_BAT_TAKEOFF;
    public static final SoundEvent ENTITY_BLAZE_AMBIENT;
    public static final SoundEvent ENTITY_BLAZE_DEATH;
    public static final SoundEvent ENTITY_BLAZE_HURT;
    public static final SoundEvent ENTITY_BOAT_PADDLE_WATER;
    public static final SoundEvent ENTITY_BOBBER_SPLASH;
    public static final SoundEvent ITEM_BOTTLE_FILL;
    public static final SoundEvent ITEM_BOTTLE_FILL_DRAGONBREATH;
    public static final SoundEvent ENTITY_CAT_AMBIENT;
    public static final SoundEvent ENTITY_CAT_DEATH;
    public static final SoundEvent ENTITY_CAT_HISS;
    public static final SoundEvent ENTITY_CAT_HURT;
    public static final SoundEvent ENTITY_CAT_PURR;
    public static final SoundEvent ENTITY_CAT_PURREOW;
    public static final SoundEvent BLOCK_CHEST_CLOSE;
    public static final SoundEvent BLOCK_CHEST_OPEN;
    public static final SoundEvent ENTITY_CHICKEN_AMBIENT;
    public static final SoundEvent ENTITY_CHICKEN_DEATH;
    public static final SoundEvent ENTITY_CHICKEN_EGG;
    public static final SoundEvent ENTITY_CHICKEN_HURT;
    public static final SoundEvent ENTITY_CHICKEN_STEP;
    public static final SoundEvent BLOCK_CLOTH_BREAK;
    public static final SoundEvent BLOCK_CLOTH_FALL;
    public static final SoundEvent BLOCK_CLOTH_STEP;
    public static final SoundEvent ENTITY_COW_AMBIENT;
    public static final SoundEvent ENTITY_COW_DEATH;
    public static final SoundEvent ENTITY_COW_HURT;
    public static final SoundEvent ENTITY_COW_STEP;
    public static final SoundEvent ENTITY_CREEPER_DEATH;
    public static final SoundEvent ENTITY_CREEPER_PRIMED;
    public static final SoundEvent ENTITY_DONKEY_AMBIENT;
    public static final SoundEvent ENTITY_DONKEY_ANGRY;
    public static final SoundEvent ENTITY_DONKEY_DEATH;
    public static final SoundEvent ENTITY_DONKEY_HURT;
    public static final SoundEvent ENTITY_EGG_THROW;
    public static final SoundEvent BLOCK_ENDERCHEST_CLOSE;
    public static final SoundEvent BLOCK_ENDERCHEST_OPEN;
    public static final SoundEvent ENTITY_ENDERDRAGON_AMBIENT;
    public static final SoundEvent ENTITY_ENDERDRAGON_DEATH;
    public static final SoundEvent ENTITY_ENDERDRAGON_FLAP;
    public static final SoundEvent ENTITY_ENDERDRAGON_GROWL;
    public static final SoundEvent ENTITY_ENDERDRAGON_HURT;
    public static final SoundEvent ENTITY_ENDERDRAGON_SHOOT;
    public static final SoundEvent ENTITY_ENDERMEN_AMBIENT;
    public static final SoundEvent ENTITY_ENDERMEN_DEATH;
    public static final SoundEvent ENTITY_ENDERMEN_HURT;
    public static final SoundEvent ENTITY_ENDERMEN_SCREAM;
    public static final SoundEvent ENTITY_ENDERMEN_STARE;
    public static final SoundEvent ENTITY_ENDERMEN_TELEPORT;
    public static final SoundEvent ENTITY_ENDERPEARL_THROW;
    public static final SoundEvent ENTITY_FIREWORK_BLAST;
    public static final SoundEvent ENTITY_FIREWORK_BLAST_FAR;
    public static final SoundEvent ENTITY_FIREWORK_LARGE_BLAST;
    public static final SoundEvent ENTITY_FIREWORK_LARGE_BLAST_FAR;
    public static final SoundEvent ENTITY_FIREWORK_LAUNCH;
    public static final SoundEvent ENTITY_FIREWORK_TWINKLE;
    public static final SoundEvent ENTITY_FIREWORK_TWINKLE_FAR;
    public static final SoundEvent BLOCK_FIRE_AMBIENT;
    public static final SoundEvent BLOCK_FIRE_EXTINGUISH;
    public static final SoundEvent ITEM_FLINTANDSTEEL_USE;
    public static final SoundEvent ENTITY_GENERIC_BIG_FALL;
    public static final SoundEvent ENTITY_GENERIC_BURN;
    public static final SoundEvent ENTITY_GENERIC_DEATH;
    public static final SoundEvent ENTITY_GENERIC_DRINK;
    public static final SoundEvent ENTITY_GENERIC_EAT;
    public static final SoundEvent ENTITY_GENERIC_EXPLODE;
    public static final SoundEvent ENTITY_GENERIC_EXTINGUISH_FIRE;
    public static final SoundEvent ENTITY_GENERIC_HURT;
    public static final SoundEvent ENTITY_GENERIC_SMALL_FALL;
    public static final SoundEvent ENTITY_GENERIC_SPLASH;
    public static final SoundEvent ENTITY_GENERIC_SWIM;
    public static final SoundEvent ENTITY_GHAST_AMBIENT;
    public static final SoundEvent ENTITY_GHAST_DEATH;
    public static final SoundEvent ENTITY_GHAST_HURT;
    public static final SoundEvent ENTITY_GHAST_SCREAM;
    public static final SoundEvent ENTITY_GHAST_SHOOT;
    public static final SoundEvent ENTITY_GHAST_WARN;
    public static final SoundEvent BLOCK_GLASS_BREAK;
    public static final SoundEvent BLOCK_GLASS_STEP;
    public static final SoundEvent BLOCK_GRASS_BREAK;
    public static final SoundEvent BLOCK_GRASS_STEP;
    public static final SoundEvent BLOCK_GRAVEL_BREAK;
    public static final SoundEvent BLOCK_GRAVEL_STEP;
    public static final SoundEvent ITEM_HOE_TILL;
    public static final SoundEvent ENTITY_HORSE_AMBIENT;
    public static final SoundEvent ENTITY_HORSE_ANGRY;
    public static final SoundEvent ENTITY_HORSE_ARMOR;
    public static final SoundEvent ENTITY_HORSE_BREATHE;
    public static final SoundEvent ENTITY_HORSE_DEATH;
    public static final SoundEvent ENTITY_HORSE_GALLOP;
    public static final SoundEvent ENTITY_HORSE_HURT;
    public static final SoundEvent ENTITY_HORSE_JUMP;
    public static final SoundEvent ENTITY_HORSE_LAND;
    public static final SoundEvent ENTITY_HORSE_STEP;
    public static final SoundEvent ENTITY_HORSE_STEP_WOOD;
    public static final SoundEvent ENTITY_HOSTILE_BIG_FALL;
    public static final SoundEvent ENTITY_HOSTILE_DEATH;
    public static final SoundEvent ENTITY_HOSTILE_HURT;
    public static final SoundEvent ENTITY_HOSTILE_SMALL_FALL;
    public static final SoundEvent ENTITY_HOSTILE_SPLASH;
    public static final SoundEvent ENTITY_HOSTILE_SWIM;
    public static final SoundEvent ENTITY_HUSK_AMBIENT;
    public static final SoundEvent ENTITY_HUSK_DEATH;
    public static final SoundEvent ENTITY_HUSK_HURT;
    public static final SoundEvent ENTITY_HUSK_STEP;
    public static final SoundEvent ENTITY_IRONGOLEM_ATTACK;
    public static final SoundEvent ENTITY_IRONGOLEM_DEATH;
    public static final SoundEvent ENTITY_IRONGOLEM_HURT;
    public static final SoundEvent ENTITY_IRONGOLEM_STEP;
    public static final SoundEvent BLOCK_IRON_DOOR_CLOSE;
    public static final SoundEvent BLOCK_IRON_DOOR_OPEN;
    public static final SoundEvent ENTITY_ITEM_BREAK;
    public static final SoundEvent ENTITY_ITEM_PICKUP;
    public static final SoundEvent BLOCK_LADDER_STEP;
    public static final SoundEvent BLOCK_LAVA_AMBIENT;
    public static final SoundEvent BLOCK_LAVA_POP;
    public static final SoundEvent ENTITY_LIGHTNING_IMPACT;
    public static final SoundEvent ENTITY_LIGHTNING_THUNDER;
    public static final SoundEvent ENTITY_LLAMA_AMBIENT;
    public static final SoundEvent ENTITY_LLAMA_ANGRY;
    public static final SoundEvent ENTITY_LLAMA_DEATH;
    public static final SoundEvent ENTITY_LLAMA_HURT;
    public static final SoundEvent ENTITY_LLAMA_STEP;
    public static final SoundEvent ENTITY_MAGMACUBE_DEATH;
    public static final SoundEvent ENTITY_MAGMACUBE_HURT;
    public static final SoundEvent ENTITY_MAGMACUBE_JUMP;
    public static final SoundEvent ENTITY_MAGMACUBE_SQUISH;
    public static final SoundEvent BLOCK_METAL_STEP;
    public static final SoundEvent ENTITY_MINECART_INSIDE;
    public static final SoundEvent ENTITY_MINECART_RIDING;
    public static final SoundEvent ENTITY_MOOSHROOM_SHEAR;
    public static final SoundEvent ENTITY_MULE_AMBIENT;
    public static final SoundEvent ENTITY_MULE_DEATH;
    public static final SoundEvent ENTITY_MULE_HURT;
    public static final SoundEvent MUSIC_CREATIVE;
    public static final SoundEvent MUSIC_CREDITS;
    public static final SoundEvent MUSIC_DRAGON;
    public static final SoundEvent MUSIC_END;
    public static final SoundEvent MUSIC_GAME;
    public static final SoundEvent MUSIC_MENU;
    public static final SoundEvent MUSIC_NETHER;
    public static final SoundEvent BLOCK_NOTE_BASEDRUM;
    public static final SoundEvent BLOCK_NOTE_BASS;
    public static final SoundEvent BLOCK_NOTE_HARP;
    public static final SoundEvent BLOCK_NOTE_HAT;
    public static final SoundEvent BLOCK_NOTE_PLING;
    public static final SoundEvent BLOCK_NOTE_SNARE;
    public static final SoundEvent ENTITY_PAINTING_BREAK;
    public static final SoundEvent ENTITY_PAINTING_PLACE;
    public static final SoundEvent ENTITY_PIG_AMBIENT;
    public static final SoundEvent ENTITY_PIG_DEATH;
    public static final SoundEvent ENTITY_PIG_HURT;
    public static final SoundEvent ENTITY_PIG_STEP;
    public static final SoundEvent BLOCK_PISTON_CONTRACT;
    public static final SoundEvent BLOCK_PISTON_EXTEND;
    public static final SoundEvent ENTITY_PLAYER_ATTACK_CRIT;
    public static final SoundEvent ENTITY_PLAYER_ATTACK_KNOCKBACK;
    public static final SoundEvent ENTITY_PLAYER_ATTACK_STRONG;
    public static final SoundEvent ENTITY_PLAYER_BIG_FALL;
    public static final SoundEvent ENTITY_PLAYER_BURP;
    public static final SoundEvent ENTITY_PLAYER_DEATH;
    public static final SoundEvent ENTITY_PLAYER_HURT;
    public static final SoundEvent ENTITY_PLAYER_LEVELUP;
    public static final SoundEvent ENTITY_PLAYER_SMALL_FALL;
    public static final SoundEvent ENTITY_PLAYER_SPLASH;
    public static final SoundEvent ENTITY_PLAYER_SWIM;
    public static final SoundEvent BLOCK_PORTAL_AMBIENT;
    public static final SoundEvent BLOCK_PORTAL_TRAVEL;
    public static final SoundEvent BLOCK_PORTAL_TRIGGER;
    public static final SoundEvent RECORD_11;
    public static final SoundEvent RECORD_13;
    public static final SoundEvent RECORD_BLOCKS;
    public static final SoundEvent RECORD_CAT;
    public static final SoundEvent RECORD_CHIRP;
    public static final SoundEvent RECORD_FAR;
    public static final SoundEvent RECORD_MALL;
    public static final SoundEvent RECORD_MELLOHI;
    public static final SoundEvent RECORD_STAL;
    public static final SoundEvent RECORD_STRAD;
    public static final SoundEvent RECORD_WAIT;
    public static final SoundEvent RECORD_WARD;
    public static final SoundEvent BLOCK_SAND_BREAK;
    public static final SoundEvent BLOCK_SAND_STEP;
    public static final SoundEvent ENTITY_SHEEP_AMBIENT;
    public static final SoundEvent ENTITY_SHEEP_DEATH;
    public static final SoundEvent ENTITY_SHEEP_HURT;
    public static final SoundEvent ENTITY_SHEEP_SHEAR;
    public static final SoundEvent ENTITY_SHEEP_STEP;
    public static final SoundEvent ENTITY_SILVERFISH_AMBIENT;
    public static final SoundEvent ENTITY_SILVERFISH_DEATH;
    public static final SoundEvent ENTITY_SILVERFISH_HURT;
    public static final SoundEvent ENTITY_SILVERFISH_STEP;
    public static final SoundEvent ENTITY_SKELETON_AMBIENT;
    public static final SoundEvent ENTITY_SKELETON_DEATH;
    public static final SoundEvent ENTITY_SKELETON_HORSE_AMBIENT;
    public static final SoundEvent ENTITY_SKELETON_HORSE_DEATH;
    public static final SoundEvent ENTITY_SKELETON_HORSE_HURT;
    public static final SoundEvent ENTITY_SKELETON_HURT;
    public static final SoundEvent ENTITY_SKELETON_STEP;
    public static final SoundEvent ENTITY_SLIME_ATTACK;
    public static final SoundEvent ENTITY_SLIME_DEATH;
    public static final SoundEvent ENTITY_SLIME_HURT;
    public static final SoundEvent ENTITY_SLIME_JUMP;
    public static final SoundEvent ENTITY_SLIME_SQUISH;
    public static final SoundEvent ENTITY_SNOWBALL_THROW;
    public static final SoundEvent BLOCK_SNOW_BREAK;
    public static final SoundEvent BLOCK_SNOW_STEP;
    public static final SoundEvent ENTITY_SPIDER_AMBIENT;
    public static final SoundEvent ENTITY_SPIDER_DEATH;
    public static final SoundEvent ENTITY_SPIDER_HURT;
    public static final SoundEvent ENTITY_SPIDER_STEP;
    public static final SoundEvent ENTITY_SPLASH_POTION_BREAK;
    public static final SoundEvent BLOCK_STONE_BREAK;
    public static final SoundEvent BLOCK_STONE_STEP;
    public static final SoundEvent ENTITY_STRAY_AMBIENT;
    public static final SoundEvent ENTITY_STRAY_DEATH;
    public static final SoundEvent ENTITY_STRAY_HURT;
    public static final SoundEvent ENTITY_STRAY_STEP;
    public static final SoundEvent ENTITY_TNT_PRIMED;
    public static final SoundEvent UI_BUTTON_CLICK;
    public static final SoundEvent ENTITY_VILLAGER_AMBIENT;
    public static final SoundEvent ENTITY_VILLAGER_DEATH;
    public static final SoundEvent ENTITY_VILLAGER_HURT;
    public static final SoundEvent ENTITY_VILLAGER_NO;
    public static final SoundEvent ENTITY_VILLAGER_TRADING;
    public static final SoundEvent ENTITY_VILLAGER_YES;
    public static final SoundEvent BLOCK_WATER_AMBIENT;
    public static final SoundEvent WEATHER_RAIN;
    public static final SoundEvent ENTITY_WOLF_AMBIENT;
    public static final SoundEvent ENTITY_WOLF_DEATH;
    public static final SoundEvent ENTITY_WOLF_GROWL;
    public static final SoundEvent ENTITY_WOLF_HOWL;
    public static final SoundEvent ENTITY_WOLF_HURT;
    public static final SoundEvent ENTITY_WOLF_PANT;
    public static final SoundEvent ENTITY_WOLF_SHAKE;
    public static final SoundEvent ENTITY_WOLF_STEP;
    public static final SoundEvent ENTITY_WOLF_WHINE;
    public static final SoundEvent BLOCK_WOODEN_DOOR_CLOSE;
    public static final SoundEvent BLOCK_WOODEN_DOOR_OPEN;
    public static final SoundEvent BLOCK_WOOD_BREAK;
    public static final SoundEvent BLOCK_WOOD_STEP;
    public static final SoundEvent ENTITY_ZOMBIE_AMBIENT;
    public static final SoundEvent ENTITY_ZOMBIE_ATTACK_DOOR_WOOD;
    public static final SoundEvent ENTITY_ZOMBIE_BREAK_DOOR_WOOD;
    public static final SoundEvent ENTITY_ZOMBIE_DEATH;
    public static final SoundEvent ENTITY_ZOMBIE_HORSE_AMBIENT;
    public static final SoundEvent ENTITY_ZOMBIE_HORSE_DEATH;
    public static final SoundEvent ENTITY_ZOMBIE_HORSE_HURT;
    public static final SoundEvent ENTITY_ZOMBIE_HURT;
    public static final SoundEvent ENTITY_ZOMBIE_INFECT;
    public static final SoundEvent ENTITY_ZOMBIE_PIG_AMBIENT;
    public static final SoundEvent ENTITY_ZOMBIE_PIG_ANGRY;
    public static final SoundEvent ENTITY_ZOMBIE_PIG_DEATH;
    public static final SoundEvent ENTITY_ZOMBIE_PIG_HURT;
    public static final SoundEvent ENTITY_ZOMBIE_STEP;
    public static final SoundEvent ENTITY_ZOMBIE_VILLAGER_AMBIENT;
    public static final SoundEvent ENTITY_ZOMBIE_VILLAGER_DEATH;
    public static final SoundEvent ENTITY_ZOMBIE_VILLAGER_HURT;

    public static final SoundEvent LIQUID_BLOCK_SPLASH;
    public static final SoundEvent RANDOM_SIZZLE;
    public static final SoundEvent RANDOM_BOIL;
    public static final SoundEvent RANDOM_LEVEL_DRAIN;
    public static final SoundEvent RANDOM_CAMERA;
    public static final SoundEvent BLOCK_CHEST_LOCKED;
    public static final SoundEvent BLOCK_BOOK_OPEN;
    public static final SoundEvent BLOCK_BOOK_PAGE;
    public static final SoundEvent BLOCK_BOOK_CLOSE;
    public static final SoundEvent RANDOM_COW_ALARM;
    public static final SoundEvent RANDOM_GUNSHOT;
    public static final SoundEvent ENTITY_DEMONSPIDER_AMBIENT;
    public static final SoundEvent ENTITY_DEMONSPIDER_HURT;
    public static final SoundEvent ENTITY_DEMONSPIDER_DEATH;
    public static final SoundEvent ENTITY_GHOUL_AMBIENT;
    public static final SoundEvent ENTITY_GHOUL_HURT;
    public static final SoundEvent ENTITY_GHOUL_DEATH;
    public static final SoundEvent ENTITY_HELLHOUND_AMBIENT;
    public static final SoundEvent ENTITY_HELLHOUND_HURT;
    public static final SoundEvent ENTITY_HELLHOUND_DEATH;
    public static final SoundEvent ENTITY_HELLHOUND_BREATHE;
    public static final SoundEvent ENTITY_INVISIBLESTALKER_AMBIENT;
    public static final SoundEvent ENTITY_INVISIBLESTALKER_HURT;
    public static final SoundEvent ENTITY_INVISIBLESTALKER_DEATH;
    public static final SoundEvent ENTITY_WIGHT_AMBIENT;
    public static final SoundEvent ENTITY_WIGHT_HURT;
    public static final SoundEvent ENTITY_WIGHT_DEATH;
    public static final SoundEvent ENTITY_SHADOW_AMBIENT;
    public static final SoundEvent ENTITY_SHADOW_HURT;
    public static final SoundEvent ENTITY_SHADOW_DEATH;
    public static final SoundEvent ENTITY_WITCH_AMBIENT;
    public static final SoundEvent ENTITY_WITCH_HURT;
    public static final SoundEvent ENTITY_WITCH_DEATH;
    public static final SoundEvent PORTAL_RUNEGATE;
    public static final SoundEvent RECORD_UNDERWORLD;
    public static final SoundEvent RECORD_DESCENT;
    public static final SoundEvent RECORD_WANDERER;
    public static final SoundEvent RECORD_LEGENDS;

    public static final SoundEvent MUSIC_UNDERWORLD;

    private static SoundEvent getRegisteredSoundEvent(String id) {
        return getRegisteredSoundEvent(new ResourceLocation(id));
    }
    
    private static SoundEvent getRegisteredSoundEvent(ResourceLocation id) {
        SoundEvent soundevent = (SoundEvent) SoundEvent.REGISTRY.getObject(id);

        if (soundevent == null) {
            throw new IllegalStateException("Invalid Sound requested: " + id);
        } else {
            return soundevent;
        }
    }

    static {
        AMBIENT_CAVE = getRegisteredSoundEvent("ambient.cave.cave");
        BLOCK_ANVIL_BREAK = getRegisteredSoundEvent("random.anvil_break");
        BLOCK_ANVIL_LAND = getRegisteredSoundEvent("random.anvil_land");
        BLOCK_ANVIL_USE = getRegisteredSoundEvent("random.anvil_use");
        ENTITY_ARMORSTAND_BREAK = getRegisteredSoundEvent("random.break");
        ENTITY_ARMORSTAND_FALL = getRegisteredSoundEvent("game.player.hurt.fall.big");
        ENTITY_ARMORSTAND_HIT = getRegisteredSoundEvent("game.player.hurt");
        ENTITY_ARROW_HIT = getRegisteredSoundEvent("random.bowhit");
        ENTITY_ARROW_SHOOT = getRegisteredSoundEvent("random.bow");
        ENTITY_BAT_AMBIENT = getRegisteredSoundEvent("mob.bat.idle");
        ENTITY_BAT_DEATH = getRegisteredSoundEvent("mob.bat.death");
        ENTITY_BAT_HURT = getRegisteredSoundEvent("mob.bat.hurt");
        ENTITY_BAT_LOOP = getRegisteredSoundEvent("mob.bat.loop");
        ENTITY_BAT_TAKEOFF = getRegisteredSoundEvent("mob.bat.takeoff");
        ENTITY_BLAZE_AMBIENT = getRegisteredSoundEvent("mob.blaze.breathe");
        ENTITY_BLAZE_DEATH = getRegisteredSoundEvent("mob.blaze.death");
        ENTITY_BLAZE_HURT = getRegisteredSoundEvent("mob.blaze.hit");
        ENTITY_BOAT_PADDLE_WATER = getRegisteredSoundEvent("game.player.swim.splash");
        ENTITY_BOBBER_SPLASH = getRegisteredSoundEvent("random.splash");
        ITEM_BOTTLE_FILL = getRegisteredSoundEvent("random.drink");
        ITEM_BOTTLE_FILL_DRAGONBREATH = getRegisteredSoundEvent("random.drink");
        ENTITY_CAT_AMBIENT = getRegisteredSoundEvent("mob.cat.meow");
        ENTITY_CAT_DEATH = getRegisteredSoundEvent("mob.cat.hitt");
        ENTITY_CAT_HISS = getRegisteredSoundEvent("mob.cat.hiss");
        ENTITY_CAT_HURT = getRegisteredSoundEvent("mob.cat.hitt");
        ENTITY_CAT_PURR = getRegisteredSoundEvent("mob.cat.purr");
        ENTITY_CAT_PURREOW = getRegisteredSoundEvent("mob.cat.purreow");
        BLOCK_CHEST_CLOSE = getRegisteredSoundEvent("random.chestclosed");
        BLOCK_CHEST_OPEN = getRegisteredSoundEvent("random.chestopen");
        ENTITY_CHICKEN_AMBIENT = getRegisteredSoundEvent("mob.chicken.say");
        ENTITY_CHICKEN_DEATH = getRegisteredSoundEvent("mob.chicken.hurt");
        ENTITY_CHICKEN_EGG = getRegisteredSoundEvent("mob.chicken.plop");
        ENTITY_CHICKEN_HURT = getRegisteredSoundEvent("mob.chicken.hurt");
        ENTITY_CHICKEN_STEP = getRegisteredSoundEvent("mob.chicken.step");
        BLOCK_CLOTH_BREAK = getRegisteredSoundEvent("dig.cloth");
        BLOCK_CLOTH_FALL = getRegisteredSoundEvent("dig.cloth");
        BLOCK_CLOTH_STEP = getRegisteredSoundEvent("step.cloth");
        ENTITY_COW_AMBIENT = getRegisteredSoundEvent("mob.cow.say");
        ENTITY_COW_DEATH = getRegisteredSoundEvent("mob.cow.hurt");
        ENTITY_COW_HURT = getRegisteredSoundEvent("mob.cow.hurt");
        ENTITY_COW_STEP = getRegisteredSoundEvent("mob.cow.step");
        ENTITY_CREEPER_DEATH = getRegisteredSoundEvent("mob.creeper.death");
        ENTITY_CREEPER_PRIMED = getRegisteredSoundEvent("creeper.primed");
        ENTITY_DONKEY_AMBIENT = getRegisteredSoundEvent("mob.horse.donkey.idle");
        ENTITY_DONKEY_ANGRY = getRegisteredSoundEvent("mob.horse.donkey.angry");
        ENTITY_DONKEY_DEATH = getRegisteredSoundEvent("mob.horse.donkey.death");
        ENTITY_DONKEY_HURT = getRegisteredSoundEvent("mob.horse.donkey.hit");
        ENTITY_EGG_THROW = getRegisteredSoundEvent("random.bow");
        BLOCK_ENDERCHEST_CLOSE = getRegisteredSoundEvent("random.chestclosed");
        BLOCK_ENDERCHEST_OPEN = getRegisteredSoundEvent("random.chestopen");
        ENTITY_ENDERDRAGON_AMBIENT = getRegisteredSoundEvent("mob.enderdragon.growl");
        ENTITY_ENDERDRAGON_DEATH = getRegisteredSoundEvent("mob.enderdragon.end");
        ENTITY_ENDERDRAGON_FLAP = getRegisteredSoundEvent("mob.enderdragon.wings");
        ENTITY_ENDERDRAGON_GROWL = getRegisteredSoundEvent("mob.enderdragon.growl");
        ENTITY_ENDERDRAGON_HURT = getRegisteredSoundEvent("mob.enderdragon.hit");
        ENTITY_ENDERDRAGON_SHOOT = getRegisteredSoundEvent("mob.enderdragon.growl");
        ENTITY_ENDERMEN_AMBIENT = getRegisteredSoundEvent("mob.endermen.idle");
        ENTITY_ENDERMEN_DEATH = getRegisteredSoundEvent("mob.endermen.death");
        ENTITY_ENDERMEN_HURT = getRegisteredSoundEvent("mob.endermen.hit");
        ENTITY_ENDERMEN_SCREAM = getRegisteredSoundEvent("mob.endermen.scream");
        ENTITY_ENDERMEN_STARE = getRegisteredSoundEvent("mob.endermen.stare");
        ENTITY_ENDERMEN_TELEPORT = getRegisteredSoundEvent("mob.endermen.portal");
        ENTITY_ENDERPEARL_THROW = getRegisteredSoundEvent("random.bow");
        ENTITY_FIREWORK_BLAST = getRegisteredSoundEvent("fireworks.blast");
        ENTITY_FIREWORK_BLAST_FAR = getRegisteredSoundEvent("fireworks.blast_far");
        ENTITY_FIREWORK_LARGE_BLAST = getRegisteredSoundEvent("fireworks.largeBlast");
        ENTITY_FIREWORK_LARGE_BLAST_FAR = getRegisteredSoundEvent("fireworks.largeBlast_far");
        ENTITY_FIREWORK_LAUNCH = getRegisteredSoundEvent("fireworks.launch");
        ENTITY_FIREWORK_TWINKLE = getRegisteredSoundEvent("fireworks.twinkle");
        ENTITY_FIREWORK_TWINKLE_FAR = getRegisteredSoundEvent("fireworks.twinkle_far");
        BLOCK_FIRE_AMBIENT = getRegisteredSoundEvent("fire.fire");
        BLOCK_FIRE_EXTINGUISH = getRegisteredSoundEvent("random.fizz");
        ITEM_FLINTANDSTEEL_USE = getRegisteredSoundEvent("fire.ignite");
        ENTITY_GENERIC_BIG_FALL = getRegisteredSoundEvent("game.player.hurt.fall.big");
        ENTITY_GENERIC_BURN = getRegisteredSoundEvent("fire.fire");
        ENTITY_GENERIC_DEATH = getRegisteredSoundEvent("game.player.die");
        ENTITY_GENERIC_DRINK = getRegisteredSoundEvent("random.drink");
        ENTITY_GENERIC_EAT = getRegisteredSoundEvent("random.eat");
        ENTITY_GENERIC_EXPLODE = getRegisteredSoundEvent("random.explode");
        ENTITY_GENERIC_EXTINGUISH_FIRE = getRegisteredSoundEvent("random.fizz");
        ENTITY_GENERIC_HURT = getRegisteredSoundEvent("game.player.hurt");
        ENTITY_GENERIC_SMALL_FALL = getRegisteredSoundEvent("game.player.hurt.fall.small");
        ENTITY_GENERIC_SPLASH = getRegisteredSoundEvent("random.splash");
        ENTITY_GENERIC_SWIM = getRegisteredSoundEvent("game.player.swim");
        ENTITY_GHAST_AMBIENT = getRegisteredSoundEvent("mob.ghast.moan");
        ENTITY_GHAST_DEATH = getRegisteredSoundEvent("mob.ghast.death");
        ENTITY_GHAST_HURT = getRegisteredSoundEvent("mob.ghast.scream");
        ENTITY_GHAST_SCREAM = getRegisteredSoundEvent("mob.ghast.scream");
        ENTITY_GHAST_SHOOT = getRegisteredSoundEvent("mob.ghast.fireball");
        ENTITY_GHAST_WARN = getRegisteredSoundEvent("mob.ghast.charge");
        BLOCK_GLASS_BREAK = getRegisteredSoundEvent("dig.glass");
        BLOCK_GLASS_STEP = getRegisteredSoundEvent("step.stone");
        BLOCK_GRASS_BREAK = getRegisteredSoundEvent("dig.grass");
        BLOCK_GRASS_STEP = getRegisteredSoundEvent("step.grass");
        BLOCK_GRAVEL_BREAK = getRegisteredSoundEvent("dig.gravel");
        BLOCK_GRAVEL_STEP = getRegisteredSoundEvent("step.gravel");
        ITEM_HOE_TILL = getRegisteredSoundEvent("step.grass");
        ENTITY_HORSE_AMBIENT = getRegisteredSoundEvent("mob.horse.idle");
        ENTITY_HORSE_ANGRY = getRegisteredSoundEvent("mob.horse.angry");
        ENTITY_HORSE_ARMOR = getRegisteredSoundEvent("mob.horse.armor");
        ENTITY_HORSE_BREATHE = getRegisteredSoundEvent("mob.horse.breathe");
        ENTITY_HORSE_DEATH = getRegisteredSoundEvent("mob.horse.death");
        ENTITY_HORSE_GALLOP = getRegisteredSoundEvent("mob.horse.gallop");
        ENTITY_HORSE_HURT = getRegisteredSoundEvent("mob.horse.hit");
        ENTITY_HORSE_JUMP = getRegisteredSoundEvent("mob.horse.jump");
        ENTITY_HORSE_LAND = getRegisteredSoundEvent("mob.horse.land");
        ENTITY_HORSE_STEP = getRegisteredSoundEvent("mob.horse.soft");
        ENTITY_HORSE_STEP_WOOD = getRegisteredSoundEvent("mob.horse.wood");
        ENTITY_HOSTILE_BIG_FALL = getRegisteredSoundEvent("game.hostile.hurt.fall.big");
        ENTITY_HOSTILE_DEATH = getRegisteredSoundEvent("game.hostile.die");
        ENTITY_HOSTILE_HURT = getRegisteredSoundEvent("game.hostile.hurt");
        ENTITY_HOSTILE_SMALL_FALL = getRegisteredSoundEvent("game.hostile.hurt.fall.small");
        ENTITY_HOSTILE_SPLASH = getRegisteredSoundEvent("game.hostile.swim.splash");
        ENTITY_HOSTILE_SWIM = getRegisteredSoundEvent("game.hostile.swim");
        ENTITY_HUSK_AMBIENT = getRegisteredSoundEvent("mob.zombie.say");
        ENTITY_HUSK_DEATH = getRegisteredSoundEvent("mob.zombie.death");
        ENTITY_HUSK_HURT = getRegisteredSoundEvent("mob.zombie.hurt");
        ENTITY_HUSK_STEP = getRegisteredSoundEvent("mob.zombie.step");
        ENTITY_IRONGOLEM_ATTACK = getRegisteredSoundEvent("mob.irongolem.throw");
        ENTITY_IRONGOLEM_DEATH = getRegisteredSoundEvent("mob.irongolem.death");
        ENTITY_IRONGOLEM_HURT = getRegisteredSoundEvent("mob.irongolem.hit");
        ENTITY_IRONGOLEM_STEP = getRegisteredSoundEvent("mob.irongolem.walk");
        BLOCK_IRON_DOOR_CLOSE = getRegisteredSoundEvent("random.door_close");
        BLOCK_IRON_DOOR_OPEN = getRegisteredSoundEvent("random.door_open");
        ENTITY_ITEM_BREAK = getRegisteredSoundEvent("random.break");
        ENTITY_ITEM_PICKUP = getRegisteredSoundEvent("random.pop");
        BLOCK_LADDER_STEP = getRegisteredSoundEvent("step.ladder");
        BLOCK_LAVA_AMBIENT = getRegisteredSoundEvent("liquid.lava");
        BLOCK_LAVA_POP = getRegisteredSoundEvent("liquid.lavapop");
        ENTITY_LIGHTNING_IMPACT = getRegisteredSoundEvent("ambient.weather.thunder");
        ENTITY_LIGHTNING_THUNDER = getRegisteredSoundEvent("ambient.weather.thunder");
        ENTITY_LLAMA_AMBIENT = getRegisteredSoundEvent("mob.horse.idle");
        ENTITY_LLAMA_ANGRY = getRegisteredSoundEvent("mob.horse.angry");
        ENTITY_LLAMA_DEATH = getRegisteredSoundEvent("mob.horse.death");
        ENTITY_LLAMA_HURT = getRegisteredSoundEvent("mob.horse.hit");
        ENTITY_LLAMA_STEP = getRegisteredSoundEvent("mob.horse.soft");
        ENTITY_MAGMACUBE_DEATH = getRegisteredSoundEvent("mob.magmacube.big");
        ENTITY_MAGMACUBE_HURT = getRegisteredSoundEvent("mob.magmacube.big");
        ENTITY_MAGMACUBE_JUMP = getRegisteredSoundEvent("mob.magmacube.jump");
        ENTITY_MAGMACUBE_SQUISH = getRegisteredSoundEvent("mob.magmacube.small");
        BLOCK_METAL_STEP = getRegisteredSoundEvent("step.stone");
        ENTITY_MINECART_INSIDE = getRegisteredSoundEvent("minecart.inside");
        ENTITY_MINECART_RIDING = getRegisteredSoundEvent("minecart.base");
        ENTITY_MOOSHROOM_SHEAR = getRegisteredSoundEvent("mob.sheep.shear");
        ENTITY_MULE_AMBIENT = getRegisteredSoundEvent("mob.horse.donkey.idle");
        ENTITY_MULE_DEATH = getRegisteredSoundEvent("mob.horse.donkey.death");
        ENTITY_MULE_HURT = getRegisteredSoundEvent("mob.horse.donkey.hit");
        MUSIC_CREATIVE = getRegisteredSoundEvent("music.game.creative");
        MUSIC_CREDITS = getRegisteredSoundEvent("music.game.end.credits");
        MUSIC_DRAGON = getRegisteredSoundEvent("music.game.end.dragon");
        MUSIC_END = getRegisteredSoundEvent("music.game.end");
        MUSIC_GAME = getRegisteredSoundEvent("music.game");
        MUSIC_MENU = getRegisteredSoundEvent("music.menu");
        MUSIC_NETHER = getRegisteredSoundEvent("music.game.nether");
        BLOCK_NOTE_BASEDRUM = getRegisteredSoundEvent("note.bd");
        BLOCK_NOTE_BASS = getRegisteredSoundEvent("note.bass");
        BLOCK_NOTE_HARP = getRegisteredSoundEvent("note.harp");
        BLOCK_NOTE_HAT = getRegisteredSoundEvent("note.hat");
        BLOCK_NOTE_PLING = getRegisteredSoundEvent("note.pling");
        BLOCK_NOTE_SNARE = getRegisteredSoundEvent("note.snare");
        ENTITY_PAINTING_BREAK = getRegisteredSoundEvent("random.break");
        ENTITY_PAINTING_PLACE = getRegisteredSoundEvent("random.break");
        ENTITY_PIG_AMBIENT = getRegisteredSoundEvent("mob.pig.say");
        ENTITY_PIG_DEATH = getRegisteredSoundEvent("mob.pig.death");
        ENTITY_PIG_HURT = getRegisteredSoundEvent("mob.pig.say");
        ENTITY_PIG_STEP = getRegisteredSoundEvent("mob.pig.step");
        BLOCK_PISTON_CONTRACT = getRegisteredSoundEvent("tile.piston.in");
        BLOCK_PISTON_EXTEND = getRegisteredSoundEvent("tile.piston.out");
        ENTITY_PLAYER_ATTACK_CRIT = getRegisteredSoundEvent("random.successful_hit");
        ENTITY_PLAYER_ATTACK_KNOCKBACK = getRegisteredSoundEvent("random.successful_hit");
        ENTITY_PLAYER_ATTACK_STRONG = getRegisteredSoundEvent("random.successful_hit");
        ENTITY_PLAYER_BIG_FALL = getRegisteredSoundEvent("game.player.hurt.fall.big");
        ENTITY_PLAYER_BURP = getRegisteredSoundEvent("random.burp");
        ENTITY_PLAYER_DEATH = getRegisteredSoundEvent("game.player.die");
        ENTITY_PLAYER_HURT = getRegisteredSoundEvent("game.player.hurt");
        ENTITY_PLAYER_LEVELUP = getRegisteredSoundEvent("random.levelup");
        ENTITY_PLAYER_SMALL_FALL = getRegisteredSoundEvent("game.player.hurt.fall.small");
        ENTITY_PLAYER_SPLASH = getRegisteredSoundEvent("game.player.swim.splash");
        ENTITY_PLAYER_SWIM = getRegisteredSoundEvent("game.player.swim");
        BLOCK_PORTAL_AMBIENT = getRegisteredSoundEvent("portal.portal");
        BLOCK_PORTAL_TRAVEL = getRegisteredSoundEvent("portal.travel");
        BLOCK_PORTAL_TRIGGER = getRegisteredSoundEvent("portal.trigger");
        RECORD_11 = getRegisteredSoundEvent("records.11");
        RECORD_13 = getRegisteredSoundEvent("records.13");
        RECORD_BLOCKS = getRegisteredSoundEvent("records.blocks");
        RECORD_CAT = getRegisteredSoundEvent("records.cat");
        RECORD_CHIRP = getRegisteredSoundEvent("records.chirp");
        RECORD_FAR = getRegisteredSoundEvent("records.far");
        RECORD_MALL = getRegisteredSoundEvent("records.mall");
        RECORD_MELLOHI = getRegisteredSoundEvent("records.mellohi");
        RECORD_STAL = getRegisteredSoundEvent("records.stal");
        RECORD_STRAD = getRegisteredSoundEvent("records.strad");
        RECORD_WAIT = getRegisteredSoundEvent("records.wait");
        RECORD_WARD = getRegisteredSoundEvent("records.ward");
        BLOCK_SAND_BREAK = getRegisteredSoundEvent("dig.sand");
        BLOCK_SAND_STEP = getRegisteredSoundEvent("step.sand");
        ENTITY_SHEEP_AMBIENT = getRegisteredSoundEvent("mob.sheep.say");
        ENTITY_SHEEP_DEATH = getRegisteredSoundEvent("mob.sheep.say");
        ENTITY_SHEEP_HURT = getRegisteredSoundEvent("mob.sheep.say");
        ENTITY_SHEEP_SHEAR = getRegisteredSoundEvent("mob.sheep.shear");
        ENTITY_SHEEP_STEP = getRegisteredSoundEvent("mob.sheep.step");
        ENTITY_SILVERFISH_AMBIENT = getRegisteredSoundEvent("mob.silverfish.say");
        ENTITY_SILVERFISH_DEATH = getRegisteredSoundEvent("mob.silverfish.kill");
        ENTITY_SILVERFISH_HURT = getRegisteredSoundEvent("mob.silverfish.hit");
        ENTITY_SILVERFISH_STEP = getRegisteredSoundEvent("mob.silverfish.step");
        ENTITY_SKELETON_AMBIENT = getRegisteredSoundEvent("mob.skeleton.say");
        ENTITY_SKELETON_DEATH = getRegisteredSoundEvent("mob.skeleton.death");
        ENTITY_SKELETON_HORSE_AMBIENT = getRegisteredSoundEvent("mob.horse.skeleton.idle");
        ENTITY_SKELETON_HORSE_DEATH = getRegisteredSoundEvent("mob.horse.skeleton.death");
        ENTITY_SKELETON_HORSE_HURT = getRegisteredSoundEvent("mob.horse.skeleton.hit");
        ENTITY_SKELETON_HURT = getRegisteredSoundEvent("mob.skeleton.hurt");
        ENTITY_SKELETON_STEP = getRegisteredSoundEvent("mob.skeleton.step");
        ENTITY_SLIME_ATTACK = getRegisteredSoundEvent("mob.slime.attack");
        ENTITY_SLIME_DEATH = getRegisteredSoundEvent("mob.slime.big");
        ENTITY_SLIME_HURT = getRegisteredSoundEvent("mob.slime.big");
        ENTITY_SLIME_JUMP = getRegisteredSoundEvent("mob.slime.big");
        ENTITY_SLIME_SQUISH = getRegisteredSoundEvent("mob.slime.small");
        ENTITY_SNOWBALL_THROW = getRegisteredSoundEvent("random.bow");
        BLOCK_SNOW_BREAK = getRegisteredSoundEvent("dig.snow");
        BLOCK_SNOW_STEP = getRegisteredSoundEvent("step.snow");
        ENTITY_SPIDER_AMBIENT = getRegisteredSoundEvent("mob.spider.say");
        ENTITY_SPIDER_DEATH = getRegisteredSoundEvent("mob.spider.death");
        ENTITY_SPIDER_HURT = getRegisteredSoundEvent("mob.spider.say");
        ENTITY_SPIDER_STEP = getRegisteredSoundEvent("mob.spider.step");
        ENTITY_SPLASH_POTION_BREAK = getRegisteredSoundEvent("game.potion.smash");
        BLOCK_STONE_BREAK = getRegisteredSoundEvent("dig.stone");
        BLOCK_STONE_STEP = getRegisteredSoundEvent("step.stone");
        ENTITY_STRAY_AMBIENT = getRegisteredSoundEvent("mob.skeleton.say");
        ENTITY_STRAY_DEATH = getRegisteredSoundEvent("mob.skeleton.death");
        ENTITY_STRAY_HURT = getRegisteredSoundEvent("mob.skeleton.hurt");
        ENTITY_STRAY_STEP = getRegisteredSoundEvent("mob.skeleton.step");
        ENTITY_TNT_PRIMED = getRegisteredSoundEvent("game.tnt.primed");
        UI_BUTTON_CLICK = getRegisteredSoundEvent("gui.button.press");
        ENTITY_VILLAGER_AMBIENT = getRegisteredSoundEvent("mob.villager.idle");
        ENTITY_VILLAGER_DEATH = getRegisteredSoundEvent("mob.villager.death");
        ENTITY_VILLAGER_HURT = getRegisteredSoundEvent("mob.villager.hit");
        ENTITY_VILLAGER_NO = getRegisteredSoundEvent("mob.villager.no");
        ENTITY_VILLAGER_TRADING = getRegisteredSoundEvent("mob.villager.haggle");
        ENTITY_VILLAGER_YES = getRegisteredSoundEvent("mob.villager.yes");
        BLOCK_WATER_AMBIENT = getRegisteredSoundEvent("liquid.water");
        WEATHER_RAIN = getRegisteredSoundEvent("ambient.weather.rain");
        ENTITY_WOLF_AMBIENT = getRegisteredSoundEvent("mob.wolf.bark");
        ENTITY_WOLF_DEATH = getRegisteredSoundEvent("mob.wolf.death");
        ENTITY_WOLF_GROWL = getRegisteredSoundEvent("mob.wolf.growl");
        ENTITY_WOLF_HOWL = getRegisteredSoundEvent("imported.mob.wolf.howl");
        ENTITY_WOLF_HURT = getRegisteredSoundEvent("mob.wolf.hurt");
        ENTITY_WOLF_PANT = getRegisteredSoundEvent("mob.wolf.panting");
        ENTITY_WOLF_SHAKE = getRegisteredSoundEvent("mob.wolf.shake");
        ENTITY_WOLF_STEP = getRegisteredSoundEvent("mob.wolf.step");
        ENTITY_WOLF_WHINE = getRegisteredSoundEvent("mob.wolf.whine");
        BLOCK_WOODEN_DOOR_CLOSE = getRegisteredSoundEvent("random.door_close");
        BLOCK_WOODEN_DOOR_OPEN = getRegisteredSoundEvent("random.door_open");
        BLOCK_WOOD_BREAK = getRegisteredSoundEvent("dig.wood");
        BLOCK_WOOD_STEP = getRegisteredSoundEvent("step.wood");
        ENTITY_ZOMBIE_AMBIENT = getRegisteredSoundEvent("mob.zombie.say");
        ENTITY_ZOMBIE_ATTACK_DOOR_WOOD = getRegisteredSoundEvent("mob.zombie.wood");
        ENTITY_ZOMBIE_BREAK_DOOR_WOOD = getRegisteredSoundEvent("mob.zombie.woodbreak");
        ENTITY_ZOMBIE_DEATH = getRegisteredSoundEvent("mob.zombie.death");
        ENTITY_ZOMBIE_HORSE_AMBIENT = getRegisteredSoundEvent("mob.horse.zombie.idle");
        ENTITY_ZOMBIE_HORSE_DEATH = getRegisteredSoundEvent("mob.horse.zombie.death");
        ENTITY_ZOMBIE_HORSE_HURT = getRegisteredSoundEvent("mob.horse.zombie.hit");
        ENTITY_ZOMBIE_HURT = getRegisteredSoundEvent("mob.zombie.hurt");
        ENTITY_ZOMBIE_INFECT = getRegisteredSoundEvent("mob.zombie.infect");
        ENTITY_ZOMBIE_PIG_AMBIENT = getRegisteredSoundEvent("mob.zombiepig.zpig");
        ENTITY_ZOMBIE_PIG_ANGRY = getRegisteredSoundEvent("mob.zombiepig.zpigangry");
        ENTITY_ZOMBIE_PIG_DEATH = getRegisteredSoundEvent("mob.zombiepig.zpigdeath");
        ENTITY_ZOMBIE_PIG_HURT = getRegisteredSoundEvent("mob.zombiepig.zpighurt");
        ENTITY_ZOMBIE_STEP = getRegisteredSoundEvent("mob.zombie.step");
        ENTITY_ZOMBIE_VILLAGER_AMBIENT = getRegisteredSoundEvent("mob.zombie.say");
        ENTITY_ZOMBIE_VILLAGER_DEATH = getRegisteredSoundEvent("mob.zombie.death");
        ENTITY_ZOMBIE_VILLAGER_HURT = getRegisteredSoundEvent("mob.zombie.hurt");

        LIQUID_BLOCK_SPLASH = getRegisteredSoundEvent("imported.liquid.block_splash");
        RANDOM_SIZZLE = getRegisteredSoundEvent("imported.random.sizzle");
        RANDOM_BOIL = getRegisteredSoundEvent("imported.random.boil");
        RANDOM_LEVEL_DRAIN = getRegisteredSoundEvent("imported.random.level_drain");
        RANDOM_CAMERA = getRegisteredSoundEvent("imported.random.camera");
        BLOCK_CHEST_LOCKED = getRegisteredSoundEvent("imported.random.chest_locked");
        BLOCK_BOOK_OPEN = getRegisteredSoundEvent("imported.random.book_open");
        BLOCK_BOOK_PAGE = getRegisteredSoundEvent("imported.random.book_page");
        BLOCK_BOOK_CLOSE = getRegisteredSoundEvent("imported.random.book_close");
        RANDOM_COW_ALARM = getRegisteredSoundEvent("imported.random.cow_alarm");
        RANDOM_GUNSHOT = getRegisteredSoundEvent("imported.random.gunshot");
        ENTITY_DEMONSPIDER_AMBIENT = getRegisteredSoundEvent("imported.mob.demonspider.say");
        ENTITY_DEMONSPIDER_HURT = getRegisteredSoundEvent("imported.mob.demonspider.hurt");
        ENTITY_DEMONSPIDER_DEATH = getRegisteredSoundEvent("imported.mob.demonspider.death");
        ENTITY_GHOUL_AMBIENT = getRegisteredSoundEvent("imported.mob.ghoul.say");
        ENTITY_GHOUL_HURT = getRegisteredSoundEvent("imported.mob.ghoul.hurt");
        ENTITY_GHOUL_DEATH = getRegisteredSoundEvent("imported.mob.ghoul.death");
        ENTITY_HELLHOUND_AMBIENT = getRegisteredSoundEvent("imported.mob.hellhound.say");
        ENTITY_HELLHOUND_HURT = getRegisteredSoundEvent("imported.mob.hellhound.hurt");
        ENTITY_HELLHOUND_DEATH = getRegisteredSoundEvent("imported.mob.hellhound.death");
        ENTITY_HELLHOUND_BREATHE = getRegisteredSoundEvent("imported.mob.hellhound.breath");
        ENTITY_INVISIBLESTALKER_AMBIENT = getRegisteredSoundEvent("imported.mob.invisiblestalker.say");
        ENTITY_INVISIBLESTALKER_HURT = getRegisteredSoundEvent("imported.mob.invisiblestalker.hurt");
        ENTITY_INVISIBLESTALKER_DEATH = getRegisteredSoundEvent("imported.mob.invisiblestalker.death");
        ENTITY_WIGHT_AMBIENT = getRegisteredSoundEvent("imported.mob.wight.say");
        ENTITY_WIGHT_HURT = getRegisteredSoundEvent("imported.mob.wight.hurt");
        ENTITY_WIGHT_DEATH = getRegisteredSoundEvent("imported.mob.wight.death");
        ENTITY_SHADOW_AMBIENT = getRegisteredSoundEvent("imported.mob.shadow.say");
        ENTITY_SHADOW_HURT = getRegisteredSoundEvent("imported.mob.shadow.hurt");
        ENTITY_SHADOW_DEATH = getRegisteredSoundEvent("imported.mob.shadow.death");
        ENTITY_WITCH_AMBIENT = getRegisteredSoundEvent("imported.mob.witch.cackle");
        ENTITY_WITCH_HURT = getRegisteredSoundEvent("imported.mob.witch.hurt");
        ENTITY_WITCH_DEATH = getRegisteredSoundEvent("imported.mob.witch.death");
        PORTAL_RUNEGATE = getRegisteredSoundEvent("imported.portal.runegate");
        RECORD_UNDERWORLD = getRegisteredSoundEvent("imported.underworld");
        RECORD_DESCENT = getRegisteredSoundEvent("imported.descent");
        RECORD_WANDERER = getRegisteredSoundEvent("imported.wanderer");
        RECORD_LEGENDS = getRegisteredSoundEvent("imported.legends");

        MUSIC_UNDERWORLD = getRegisteredSoundEvent(new ResourceLocation("bgs", "music.game.underworld"));
    }
}